### ISSUE TITLE
Information about versions of the specs

### ISSUE THREAD

**Issue by manuelafm** [arsv/riscv-qemu#1]
(Great work going ahead with the implementation of the qemu-user mode, thanks!)

As a wishlist, I think that it would be useful if it was included somewhere the versions of the specs that are implemented.  I am not sure if the Priviledge/Supervisor spec is relevant for the qemu-user emulation, but since even the Userland spec has recent changes, it would be a useful piece of information to have.

**Comment by arsv** [comment]
Updated README. The code follows current user-level ISA spec 2.1.

The privileged spec is indeed mostly irrelevant at this point.
I'm using 1.9 but I think the only piece that went into the actual code so far is fcsr address.
And that's a part of user-level ISA really, not sure why it's in the privileged spec.
